table Calendar
	lineageTag: 73f0d1ac-f37c-40bc-b787-101c43c73642

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: d44fd36b-9293-4c3d-86c0-efb0bd9c32f0
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: ab01e665-f4ee-4819-b41c-c0ad87490406
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 0827ffaa-260f-4563-8eab-930c86d56834
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: a14bb390-96ae-49db-bbe3-486ab23b7eef
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 8510fb55-39d1-4804-a14b-eb9186b8a738
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: cd61753a-d8b9-48e0-bf72-a7ab590f75cb
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 921ff7cf-bf47-4bc6-8685-f72df051ebb0
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 90165bcd-f4a1-4923-b746-86264df7897b
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: f828b55c-08b2-453b-a10e-85dec4534024

		level Year
			ordinal: 0
			column: Year
			lineageTag: a433d16a-b04e-4007-b72e-ff5442851fbe

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 2328e3f5-b2d4-4d69-b271-4789eb5b9d19

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 6d05b443-a1ca-4d1f-b141-f3d6c4874284

		level Day
			ordinal: 3
			column: Day
			lineageTag: 82f666c2-74a1-4f06-820c-69507c9b3a1d


	partition 'Calendar-eb3edd3b-844d-4854-a4a8-002c99e0c7eb' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

