table Calendar
	lineageTag: 419f255a-4229-47ff-9582-f240cf009346

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 121361aa-dd10-4d35-8436-92dfec4e205a
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 589f36db-b7db-4d93-80ac-ebda3a3b29b3
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 6b43482d-a82d-4f8f-b887-bdc6f3e4cafd
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 7369a591-3d4b-4747-b72a-de6a974f4a5d
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: bb6823b7-63ba-407c-bf30-3b35439c2327
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: a9816085-bf69-4f3f-915b-476e1495c61b
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 7c03a06c-ac3f-43f3-ae91-263079d3986b
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: fe2c5e79-7eb6-4289-9644-bfbe83cd08a9
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: f4d6a57d-7c15-4619-a26e-64166a12b925

		level Year
			ordinal: 0
			column: Year
			lineageTag: d4a0c573-a1c3-49a2-ae38-6a34a4daa5ca

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 08b6cab2-ff13-45b6-8706-9949051d7c06

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 1468852b-f706-4793-8e3f-aa397b8981cb

		level Day
			ordinal: 3
			column: Day
			lineageTag: d22084a5-2301-4273-ae18-6bc9678e73f4


	partition 'Calendar-52bbbc52-ffec-436f-8438-b7a0bedb3a56' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

