table Products
	lineageTag: a5ac560f-9dd1-48f0-ad86-a70797d1bcb3

	column ProductID
		dataType: int64
		lineageTag: 6ff9b59e-12b4-4589-bf77-28358a85b4a8
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: be97c256-5d89-4751-a178-12f3d482cbc9
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 25adc2f9-490f-44e6-9df5-7ce1621abfb3
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column SubCategory
		dataType: string
		lineageTag: 59ba2d49-4549-4b54-ac2e-716a739cffab
		summarizeBy: none
		sourceColumn: SubCategory

		annotation SummarizationSetBy = Automatic

	column UnitCost
		dataType: double
		lineageTag: b181dba0-9334-477e-be61-ae6bfc67434f
		summarizeBy: none
		sourceColumn: UnitCost

		annotation SummarizationSetBy = Automatic

	partition 'Products-5873b95b-fb2f-44e7-a49e-b4b38a69f9af' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\\Products.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
				,
				    SelectedColumns = Table.SelectColumns(PromotedHeaders, {"ProductID", "ProductName", "Category", "SubCategory", "UnitCost"})
				,
				    #"Changed Type" = Table.TransformColumnTypes(SelectedColumns, {{"ProductID", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

