table Calendar
	lineageTag: b69e7380-92fd-47e9-b25d-f7faa90eed5e

	measure 'Year To Date' = TOTALYTD([Total Sales], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: b0feee45-5558-4ad6-9291-750d5829acb6

	measure 'Previous Year' = CALCULATE([Total Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: deae146d-9cb9-44ab-a90e-78fbec19bc0c

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 0e65a447-3a80-41a1-a0d3-71ba554c2f72

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: bdbb12f6-16d3-4765-afa8-5a0621ebd65e
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: ae9f81a3-cf77-42a9-b9ca-7764f668a0bf
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: acdaf07f-062f-4e1b-9acf-d1e5a7fc9f02
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 7ef80b17-c554-4004-bf15-8c5e42a82791
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: d7e4af73-60ad-45bc-8549-2ed905e71435
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: ded364b2-f8e0-4968-8327-2adf5c441c8e
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: a0999970-f33a-421a-aa08-6591ed89fd1a
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: d38c8024-8719-4371-84bd-e8aade000158
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 2386eb31-072b-482e-8020-df84db44c2d6

		level Year
			ordinal: 0
			column: Year
			lineageTag: f7b5ee5e-851a-49a8-91ea-d0f64a80a4b1

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 3ac14200-7902-471b-99f4-c91123218b53

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 721d9439-26c1-44bd-89e2-04c6c6d2d3f2

		level Day
			ordinal: 3
			column: Day
			lineageTag: 25aa7f5b-cf0e-46f1-b054-fe71235bb251


	partition 'Calendar-50532f41-956e-4290-85ab-c6c64dd7d958' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

