"""Tests for v9 visual type mappings, custom visual GUIDs,
auto-generated measures system, and Qlik extension mapping."""

import unittest

from powerbi_import.visual_generator import (
    VISUAL_TYPE_MAP,
    CUSTOM_VISUAL_GUIDS,
    QLIK_EXTENSION_MAP,
    get_auto_generated_measures,
    clear_auto_generated_measures,
    _add_auto_measure,
    resolve_extension_visual,
    resolve_custom_visual_type,
)


# ── New Visual Type Mappings (14 tests) ──────────────────────────


class TestV9VisualTypeMappings(unittest.TestCase):
    """Verify the 14 new visual type entries added in v9."""

    def test_makepoint_maps_to_azure_map(self):
        self.assertEqual(VISUAL_TYPE_MAP["makepoint"], "azureMap")

    def test_spatial_maps_to_azure_map(self):
        self.assertEqual(VISUAL_TYPE_MAP["spatial"], "azureMap")

    def test_azuremap_maps_to_azure_map(self):
        self.assertEqual(VISUAL_TYPE_MAP["azuremap"], "azureMap")

    def test_violinplot_maps_to_box_and_whisker(self):
        self.assertEqual(VISUAL_TYPE_MAP["violinplot"], "boxAndWhisker")

    def test_violin_maps_to_box_and_whisker(self):
        self.assertEqual(VISUAL_TYPE_MAP["violin"], "boxAndWhisker")

    def test_parallelcoordinates_maps_to_line_chart(self):
        self.assertEqual(VISUAL_TYPE_MAP["parallelcoordinates"], "lineChart")

    def test_parallel_coordinates_dash_maps_to_line_chart(self):
        self.assertEqual(VISUAL_TYPE_MAP["parallel-coordinates"], "lineChart")

    def test_calendarheatmap_maps_to_matrix(self):
        self.assertEqual(VISUAL_TYPE_MAP["calendarheatmap"], "matrix")

    def test_orgchart_maps_to_decomposition_tree(self):
        self.assertEqual(VISUAL_TYPE_MAP["orgchart"], "decompositionTree")

    def test_radar_maps_to_line_chart(self):
        self.assertEqual(VISUAL_TYPE_MAP["radar"], "lineChart")

    def test_dendrogram_maps_to_decomposition_tree(self):
        self.assertEqual(VISUAL_TYPE_MAP["dendrogram"], "decompositionTree")


# ── New Custom Visual GUIDs (9 tests) ────────────────────────────


class TestV9CustomVisualGUIDs(unittest.TestCase):
    """Verify the 9 new custom visual GUID entries added in v9."""

    _EXPECTED_KEYS = {"guid", "name", "class", "roles"}

    def _assert_guid_entry(self, key, expected_guid):
        self.assertIn(key, CUSTOM_VISUAL_GUIDS)
        entry = CUSTOM_VISUAL_GUIDS[key]
        self.assertEqual(entry["guid"], expected_guid)
        self.assertTrue(self._EXPECTED_KEYS.issubset(entry.keys()),
                        f"Missing keys in '{key}': {self._EXPECTED_KEYS - entry.keys()}")

    def test_violin_guid(self):
        self._assert_guid_entry("violin", "ViolinPlot1.0.0")

    def test_parallelcoordinates_guid(self):
        self._assert_guid_entry("parallelcoordinates", "ParallelCoordinates1.0.0")

    def test_calendar_guid(self):
        self._assert_guid_entry("calendar", "Calendar1.0.0")

    def test_orgchart_guid(self):
        self._assert_guid_entry("orgchart", "OrgChart1.0.0")

    def test_timeline_guid(self):
        self._assert_guid_entry("timeline", "Timeline1.0.0")

    def test_radar_guid(self):
        self._assert_guid_entry("radar", "RadarChart1.0.0")

    def test_dendrogram_guid(self):
        self._assert_guid_entry("dendrogram", "Dendrogram1.0.0")

    def test_sunburst_guid(self):
        self._assert_guid_entry("sunburst", "Sunburst1.0.0")

    def test_all_entries_have_required_keys(self):
        for key, entry in CUSTOM_VISUAL_GUIDS.items():
            with self.subTest(key=key):
                self.assertTrue(
                    self._EXPECTED_KEYS.issubset(entry.keys()),
                    f"'{key}' missing keys: {self._EXPECTED_KEYS - entry.keys()}",
                )


# ── Auto-Generated Measures System (5 tests) ─────────────────────


class TestAutoGeneratedMeasures(unittest.TestCase):
    """Verify the auto-generated measures bookkeeping helpers."""

    def setUp(self):
        clear_auto_generated_measures()

    def tearDown(self):
        clear_auto_generated_measures()

    def test_initial_list_is_empty(self):
        self.assertEqual(get_auto_generated_measures(), [])

    def test_add_single_measure(self):
        _add_auto_measure("Rank", "RANKX(ALL(T), [Sales])")
        measures = get_auto_generated_measures()
        self.assertEqual(len(measures), 1)
        self.assertEqual(measures[0]["name"], "Rank")
        self.assertEqual(measures[0]["expression"], "RANKX(ALL(T), [Sales])")
        self.assertEqual(measures[0]["displayFolder"], "Auto-Generated")

    def test_clear_resets_list(self):
        _add_auto_measure("M1", "SUM(X)")
        clear_auto_generated_measures()
        self.assertEqual(get_auto_generated_measures(), [])

    def test_multiple_adds_accumulate(self):
        _add_auto_measure("M1", "SUM(X)")
        _add_auto_measure("M2", "AVERAGE(Y)")
        _add_auto_measure("M3", "COUNT(Z)")
        self.assertEqual(len(get_auto_generated_measures()), 3)

    def test_returned_list_is_copy(self):
        _add_auto_measure("M1", "SUM(X)")
        first = get_auto_generated_measures()
        first.append({"name": "fake"})
        self.assertEqual(len(get_auto_generated_measures()), 1)


# ── Qlik Extension Mapping (8 tests) ─────────────────────────────


class TestQlikExtensionMapping(unittest.TestCase):
    """Verify the Qlik extension → PBI visual mapping."""

    def test_extension_map_has_at_least_16_entries(self):
        self.assertGreaterEqual(len(QLIK_EXTENSION_MAP), 16)

    def test_smart_pivot_resolves(self):
        pbi_type, note = resolve_extension_visual("qlik-smart-pivot")
        self.assertEqual(pbi_type, "pivotTable")
        self.assertIsNotNone(note)

    def test_word_cloud_resolves(self):
        pbi_type, note = resolve_extension_visual("qlik-word-cloud")
        self.assertEqual(pbi_type, "wordCloud")
        self.assertIsNotNone(note)

    def test_sankey_chart_resolves(self):
        pbi_type, note = resolve_extension_visual("qlik-sankey-chart-ext")
        self.assertEqual(pbi_type, "sankeyDiagram")
        self.assertIsNotNone(note)

    def test_unknown_extension_returns_none(self):
        pbi_type, note = resolve_extension_visual("unknown-ext")
        self.assertIsNone(pbi_type)
        self.assertIsNone(note)

    def test_none_extension_returns_none(self):
        pbi_type, note = resolve_extension_visual(None)
        self.assertIsNone(pbi_type)
        self.assertIsNone(note)

    def test_case_insensitive_lookup(self):
        pbi_type, note = resolve_extension_visual("Qlik-Smart-Pivot")
        self.assertEqual(pbi_type, "pivotTable")

    def test_note_contains_extension_id(self):
        _, note = resolve_extension_visual("qlik-bullet-chart")
        self.assertIn("qlik-bullet-chart", note)


# ── resolve_custom_visual_type() with new types (5 tests) ────────


class TestResolveCustomVisualType(unittest.TestCase):
    """Verify resolve_custom_visual_type() with v9 types."""

    def test_violin_custom_visual_enabled(self):
        vtype, guid_info = resolve_custom_visual_type("violin", use_custom_visuals=True)
        self.assertIsNotNone(guid_info)
        self.assertEqual(guid_info["guid"], "ViolinPlot1.0.0")

    def test_violin_custom_visual_disabled(self):
        vtype, guid_info = resolve_custom_visual_type("violin", use_custom_visuals=False)
        self.assertEqual(vtype, "boxAndWhisker")
        self.assertIsNone(guid_info)

    def test_radar_custom_visual_enabled(self):
        vtype, guid_info = resolve_custom_visual_type("radar", use_custom_visuals=True)
        self.assertIsNotNone(guid_info)
        self.assertEqual(guid_info["guid"], "RadarChart1.0.0")

    def test_unknown_type_falls_back_to_tableEx(self):
        vtype, guid_info = resolve_custom_visual_type("unknown_type")
        self.assertEqual(vtype, "tableEx")
        self.assertIsNone(guid_info)

    def test_none_input_falls_back_to_tableEx(self):
        vtype, guid_info = resolve_custom_visual_type(None)
        self.assertEqual(vtype, "tableEx")
        self.assertIsNone(guid_info)


if __name__ == "__main__":
    unittest.main()
