table Calendar
	lineageTag: 5bcc1014-3140-4742-a500-4e931d01f613

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 17f551b0-6fe0-40aa-a277-c137b2af3648
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 382a4894-0a1c-430f-9b4b-8054aeb4edbe
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 50285cca-3069-4a54-893b-16ddeda8e349
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: db9dd8f6-8ac3-40e0-a8e5-9792bd414642
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: c4937b4b-9d55-4bf8-abed-e5c8c22193f2
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 4afe1cb4-cd99-40f3-83a8-1b2c7d2e4180
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: d163e0ce-468a-4947-b8fa-26572bab2afe
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: aa15f239-c6bd-4bdb-a110-877d20062bcb
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: fe187604-a92e-41a6-a80f-ad8be989872e

		level Year
			ordinal: 0
			column: Year
			lineageTag: 9881da3a-66aa-4e7c-a230-ecb1d6365e10

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 10d0d7e1-d225-4b99-a17d-b99df1079491

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 863f0bc4-7abc-4969-b258-473517ef6f01

		level Day
			ordinal: 3
			column: Day
			lineageTag: 2df23396-0cda-492f-bbb3-0202509f1445


	partition 'Calendar-54344761-b3f3-4c70-829a-26b0cf08d255' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

