table Products
	lineageTag: 684288b3-131b-4c24-b553-66792e518475

	column ProductID
		dataType: int64
		lineageTag: 570621a1-e2ca-4e77-85f0-0423518d2a14
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: 2d202243-9f7e-4d33-be59-ab8318b2164a
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 513814ec-2d24-446e-9a5e-134b3472489a
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column SubCategory
		dataType: string
		lineageTag: cda9c66c-760c-478d-9d40-80c23b6e755a
		summarizeBy: none
		sourceColumn: SubCategory

		annotation SummarizationSetBy = Automatic

	column UnitCost
		dataType: double
		lineageTag: 267c4569-ff4f-4670-99a0-a56eca537d27
		summarizeBy: none
		sourceColumn: UnitCost

		annotation SummarizationSetBy = Automatic

	partition 'Products-7e60c517-eba0-4862-9f1f-419d7ec18ec5' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\\Products.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
				,
				    SelectedColumns = Table.SelectColumns(PromotedHeaders, {"ProductID", "ProductName", "Category", "SubCategory", "UnitCost"})
				,
				    #"Changed Type" = Table.TransformColumnTypes(SelectedColumns, {{"ProductID", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

