table Calendar
	lineageTag: b7dd83de-2539-4022-9802-d4d8da9e6591

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: d3d1a798-e5a6-4c30-9ad0-1ee083738bc5
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: e36ec0f5-5628-474d-8f63-dc21f679b210
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: a6f05257-a09b-4168-be65-c1ba94d0e396
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 45173bd6-7a95-461c-b36f-96e848c6e62a
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 10de8617-ec17-4697-8931-cfd3b5071f4f
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: f4fd36af-44ed-4124-bf55-f7f45608520c
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 66ace0c8-c8bf-470f-a645-79696e085541
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 38ee7ecd-5cef-422e-a106-1b7cf1fae30e
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 5434a8fd-f21b-40ea-8e24-ee6314715f75

		level Year
			ordinal: 0
			column: Year
			lineageTag: bc533fee-76c1-41d9-979f-f4af607e7d91

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: e0114ff0-0cb0-4a9b-b761-6b828590f3cf

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: c89e58cf-2f6b-49e4-9f4c-8901f4891910

		level Day
			ordinal: 3
			column: Day
			lineageTag: 5d343b77-5ac2-4025-b954-b3f4c7f060a4


	partition 'Calendar-f7463e34-5203-4f82-8c99-ad1c99ed2a87' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

