table Products
	lineageTag: f75ca183-0a64-4f70-b920-5f88cff759d3

	column ProductID
		dataType: int64
		lineageTag: 8eb4a4b0-1888-4de4-a6d1-14d10f6ce28c
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: 59ab1d03-06ab-471d-8852-3cd404b9c3e5
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: b33cb388-786a-49be-ba08-42fe70dc8407
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column SubCategory
		dataType: string
		lineageTag: e473ed24-6f4a-4f06-8118-32bccac21409
		summarizeBy: none
		sourceColumn: SubCategory

		annotation SummarizationSetBy = Automatic

	column UnitCost
		dataType: double
		lineageTag: 8e3505ed-bb88-4878-b39c-ec77f5e71f85
		summarizeBy: none
		sourceColumn: UnitCost

		annotation SummarizationSetBy = Automatic

	partition 'Products-404b79b2-9054-493a-aa9b-81946f7b4694' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\\Products.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
				,
				    SelectedColumns = Table.SelectColumns(PromotedHeaders, {"ProductID", "ProductName", "Category", "SubCategory", "UnitCost"})
				,
				    #"Changed Type" = Table.TransformColumnTypes(SelectedColumns, {{"ProductID", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

