table Products
	lineageTag: 86a8d261-2c71-4c91-af7f-eb24f77e444b

	column ProductID
		dataType: int64
		lineageTag: 97380529-0019-4b3c-9e17-6b576fd114ea
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: 0c91852b-d9e2-4b0c-bdc4-5574b0a4b51b
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column CategoryID
		dataType: int64
		lineageTag: 9d70acb0-14ec-4601-b55c-27c17da4a72f
		summarizeBy: none
		sourceColumn: CategoryID

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: double
		lineageTag: 7c79bff8-fe80-4eea-9a1e-0c4e46ea471b
		summarizeBy: none
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

	partition 'Products-f416dca1-d3a0-41a3-a973-66655a462e8a' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\\Products.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
				,
				    SelectedColumns = Table.SelectColumns(PromotedHeaders, {"ProductID", "ProductName", "CategoryID", "UnitPrice"})
				,
				    #"Changed Type" = Table.TransformColumnTypes(SelectedColumns, {{"ProductID", Int64.Type}, {"CategoryID", Int64.Type}, {"UnitPrice", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

