table Calendar
	lineageTag: 826d369f-6d40-46d0-ae0c-9dafff5bf5aa

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 586609da-07b9-4e06-aad9-666ec976be4d
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: bf84f961-c66c-4729-b678-3e6a77613dc4
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 37da96ed-20e3-4914-8855-749e65c58c87
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: c2b02363-2419-4ac8-884c-c3fccb892157
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 39fed06a-1a90-4c5c-80f2-05b15e73d1ea
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 1db6087f-de6c-4609-bc4b-23731bbc89bb
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 22ac4d57-56d5-4551-9f6b-a32fa7a6d7c2
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 9d42e6ef-f812-4555-8b59-45db844278be
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: ec1e51d6-b146-4707-9a39-02eef3973314

		level Year
			ordinal: 0
			column: Year
			lineageTag: acc80b1d-08fd-4aaa-b208-8b8954e7ad17

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: f3118fa4-1e67-4352-a9cf-d3e2109f8392

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: e04ea2a5-8182-4315-b39c-22a5b680322e

		level Day
			ordinal: 3
			column: Day
			lineageTag: e877cdf4-eda0-4404-a399-7388570e172b


	partition 'Calendar-8d5f6ada-b4b8-4148-935e-a1d36f3cd1a4' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

