table Calendar
	lineageTag: 757ebedf-609f-43ed-9372-8df95236ea0f

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: fc079fca-56f5-44cf-a98d-b864d8666afa
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 2fec00d5-dcb9-43cd-a690-6ad81e92a1a0
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: c8612278-7bf8-4c15-a4f8-1c7e4c1544ef
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: f39bb385-9b7d-4031-8115-597e55572fac
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: baa8a474-6d4c-46d0-a655-9fec0265e331
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 38a3aea8-749d-4f9c-ad40-8769a7685ac0
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: e2dfa3cd-251d-4db5-9d0a-8c74f81d34f4
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 3bf90a98-72d6-4743-be04-5208941b38af
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 6c8954af-aa69-45f3-941d-5fbc98844fd2

		level Year
			ordinal: 0
			column: Year
			lineageTag: 95f64338-377b-413d-a1dd-2e15b6a80b63

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 5fb2b284-f5c3-44d5-ba6b-18e6df8e4034

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: afe1e8bf-7f82-4953-8236-0eed5f49e408

		level Day
			ordinal: 3
			column: Day
			lineageTag: fe2ac8d5-56fb-4f89-84dd-4b2e11f156ab


	partition 'Calendar-04773539-c346-4d3b-98d8-a0ff38684ae8' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

