table Calendar
	lineageTag: 6277a3f0-70e0-40fe-a88d-833747695419

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 5c2ad5a7-c9b8-49ab-acc8-7776a72f54a4
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 7d32b364-18d0-4a2b-97d4-e1e08b0e9bbc
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: bbf56e7f-04e8-4192-885e-e136f10130ec
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: cc7064f6-84bb-4c25-8cd2-955b2999f0c9
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: c5668f62-9c37-4151-a636-b5f3981c5da8
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: fe104d65-20c9-4d95-a6fc-e2d1f58b727c
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 631a90d8-5df5-468d-8f43-a0155730c701
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 349d8293-ef6f-4a1e-af82-edfa6d65785b
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: b83681c6-b214-43bd-a0d3-0a7b573fe3b7

		level Year
			ordinal: 0
			column: Year
			lineageTag: 870b7362-eb8c-4fd5-8410-2cf48062a718

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: f317d93e-c32c-4eaf-a832-c228c9f04025

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 6f1fea60-412f-4014-9b08-4ddc4761cf0c

		level Day
			ordinal: 3
			column: Day
			lineageTag: 05ee395d-6481-4916-9240-a35dd661cec9


	partition 'Calendar-596f9207-c33b-4cb5-9c58-d5b2e32e2dae' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

