table Sales
	lineageTag: 0ea85e67-6356-4403-bbee-17c6cf237e7b

	column ProductName
		dataType: string
		lineageTag: 37e60396-6be2-4a42-8db3-f2ebe6afd039
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column SalesDate
		dataType: dateTime
		formatString: General Date
		lineageTag: d22a0e0a-e22b-4062-9185-0b284ea84634
		summarizeBy: none
		sourceColumn: SalesDate
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Revenue
		dataType: double
		lineageTag: a09cdc0b-4480-47b5-ae9d-af6a5e902ae4
		summarizeBy: none
		sourceColumn: Revenue

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		lineageTag: 626a21ec-0009-4176-a402-29b6603feb08
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	partition 'Sales-adeee376-c6b6-46dc-a37b-e139a4611ca5' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Data\file.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {{"ProductName", type text}, {"SalesDate", type text}, {"Revenue", type text}, {"Quantity", type text}})
				in
				    ChangedTypes

	annotation PBI_ResultType = Table

