table Calendar
	lineageTag: b1b5e91d-3d72-44f2-81ad-44af4bbd2102

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 172a023d-2b2c-4d1a-9622-89d4c1c22852
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: efcd66a2-e0cf-406c-af20-4e0e7db8a595
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: eeda4a09-f9e4-432f-aa49-24691502febb
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 905513d3-1eb5-4f8d-8eb6-17b25be7ac52
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 74f2bbe2-d591-479a-81ac-980f3424a5d0
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: a55ecc7b-3de9-415e-b2d4-e84f8166d52b
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: c5c82ca4-b49b-4e94-ac16-5a6c200aedf2
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 40650896-9f6d-4941-b0e2-2bd5a56dfb10
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 330fc596-b822-4186-9950-cd6ff88ab3ae

		level Year
			ordinal: 0
			column: Year
			lineageTag: 5204444a-98f6-4913-af60-2f9c88e1c514

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: e0c331d0-0843-4238-8128-abcbafbffdcd

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: fdec528d-a59c-4c1e-95f7-f56696743a65

		level Day
			ordinal: 3
			column: Day
			lineageTag: 7f7a1fdf-e724-46a8-90dd-3afe5cfeddbe


	partition 'Calendar-9e9342cd-eedf-4164-89e6-cdf8ee190ea7' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

