table Customers
	lineageTag: 853bddb2-b44b-4184-b4f0-b970720068f5

	column CustomerID
		dataType: int64
		lineageTag: c8620915-71bb-414e-abbe-83b5ce80c098
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column CustomerName
		dataType: string
		lineageTag: c329b5f3-7d64-49dc-ad9a-4bae38c91969
		summarizeBy: none
		sourceColumn: CustomerName

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: ae1e67be-caab-4283-9fc4-3fc238790581
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 1b53734d-20de-499e-9804-18500cf8ad8b
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: bb9e96ce-c345-48b0-8552-9acfe014eff9
		summarizeBy: none
		sourceColumn: Country
		dataCategory: Country

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 973bf042-cf6c-49c5-874a-59d0a1535366
		summarizeBy: none
		sourceColumn: City
		dataCategory: City

		annotation SummarizationSetBy = Automatic

	partition 'Customers-30621a65-33fd-433e-b36d-845e3b82a7fc' = m
		mode: import
		source =
				let
				    Source = Sql.Database("localhost", "master"),
				    Table = Source{[Schema="dbo",Item="Customers"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Table, {{"CustomerID", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

