table Calendar
	lineageTag: c9ceed42-e52c-464f-8941-32ab97bcf028

	measure 'Year To Date' = TOTALYTD([CA Total], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: b7b6052b-2b20-40a8-8305-81aaab76ec9e

	measure 'Previous Year' = CALCULATE([CA Total], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 8a0239df-e533-45af-bd9c-50a26c55710b

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: bd069dd3-7e98-47cd-8d57-2039dd4119d2

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: bc42ae36-0bea-4391-8043-440824509966
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: ef51bb2c-9e77-491a-903e-26a0e11ce110
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: f9441f64-d79b-497c-b172-c2bee221f680
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: e29d9835-cbb2-4603-902f-e5d5afe007ae
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 1975ddea-d495-401c-a971-47c3ce159c18
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: d72bb3a5-b6eb-43e6-802d-34c80c72d3ef
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 892ce96b-0224-4dea-b215-8c2488ceedf3
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 7f2f02f0-b37b-4749-a365-9fbe707d1c3b
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 66c989bb-53b7-4138-afc9-021e816d1002

		level Year
			ordinal: 0
			column: Year
			lineageTag: 1e0c9858-a92e-4245-ab3c-c5d99719d63e

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 7414b831-a4be-4af0-9313-05e231bda994

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 336e5320-669b-4ae7-8bea-1c14422fa15f

		level Day
			ordinal: 3
			column: Day
			lineageTag: 68c51a6c-9b95-460b-b41a-b0c36dbc8393


	partition 'Calendar-b678d8d5-880d-4a00-b097-bfd6a00b518d' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

