table Calendar
	lineageTag: d183c380-9511-45bf-a5f5-b4ba31d55da1

	measure 'Year To Date' = TOTALYTD([CA Total], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 0a3daf4f-cab4-4f6f-85cc-e20b2fa740f7

	measure 'Previous Year' = CALCULATE([CA Total], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 14a02c59-df0b-4b5a-af8d-bee521a93687

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 8d671b16-5169-48e0-8db8-a0831d4cbab7

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 043ada1f-8c52-40ed-993f-9ff9fe9eb947
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: ac16ea23-43c6-4038-9613-139d2993a38c
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 7f177bbf-d8bc-4af0-ba73-e5991b09d02f
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 06baf5e2-7f37-4a23-84f1-78e9c4ebbf94
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: fa4bf53b-24e6-4e2c-8a8f-4ec1787d4402
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 1ba5a23a-20f6-43d8-b2e1-dfaac08fcf30
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: c0d750a1-a8f5-4407-a096-83fe60dd76ae
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 9ecaf4f2-61f0-4a11-a9db-4d99a5383b5d
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: fe0e08a5-a487-4d62-99e6-dcde75d945dc

		level Year
			ordinal: 0
			column: Year
			lineageTag: 4acf392d-8bb3-435f-8c45-3934188f960f

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: c265cca1-b5e5-4105-b6f0-f21b238f2c54

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: ed7d6ab8-7fe3-4a04-ad5b-4b45532a7852

		level Day
			ordinal: 3
			column: Day
			lineageTag: 34dfdd78-f418-4c5f-b7de-57836ae4c703


	partition 'Calendar-60e42edf-26ef-4a79-87b3-0b1fc003cbe3' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

