table Calendar
	lineageTag: f5ea0293-14fa-40dc-9135-5c011698be72

	measure 'Year To Date' = TOTALYTD([CA Total], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: c2a33fb1-b65c-42ea-96b7-d9c9ffe40310

	measure 'Previous Year' = CALCULATE([CA Total], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: da1eb493-9c6b-40ce-baf2-5b244a4cd5e4

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: e8803273-ce14-48bb-a044-0a9a0d4e3131

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: b45a396a-df7b-4037-b755-d37688465ee9
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 3ced8c6e-3dd4-4996-83d1-e7cb86157de1
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 2761cd83-a855-4ba2-b467-df34bc385e7d
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: b6a0cb58-0f70-4499-8e70-ea293f27707a
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 48f819d1-31cd-4a65-ba5d-4649e5b76340
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 7bd05c0a-20a1-4a5d-8f53-4286b6406acb
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: de4dcbfd-ea4b-42cd-bdc9-4f85ac7e3e2e
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 1bcd248f-a6bd-4619-97f0-fdcdd5425ffd
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 35c8b27e-db82-4ab5-b233-233e11425822

		level Year
			ordinal: 0
			column: Year
			lineageTag: d3cea601-3cb1-479c-a5d2-8d21129aa2e7

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 69acdb2e-ce91-4057-8624-d1a5f14ae26f

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 26271f1d-5d68-4b2b-871b-c8b2d4d9db59

		level Day
			ordinal: 3
			column: Day
			lineageTag: d9c106b4-f7e1-4f9a-b125-4f1b3954748d


	partition 'Calendar-50334426-bfb3-4e56-9b41-a121724d7522' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

