table Customers
	lineageTag: 9da2dfaa-097e-428f-a4b2-90d063de84a6

	column CustomerID
		dataType: int64
		lineageTag: 43e70326-2aa8-4218-9573-5a94f9d51199
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column CustomerName
		dataType: string
		lineageTag: a711306e-503e-4ddb-9af0-fdeeb2d4423c
		summarizeBy: none
		sourceColumn: CustomerName

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 52d6c962-1120-460d-a6e6-8f3a48bfe4d0
		summarizeBy: none
		sourceColumn: Country
		dataCategory: Country

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 334c24ce-1f5d-4cfa-9248-8ebe61049e1f
		summarizeBy: none
		sourceColumn: City
		dataCategory: City

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 06df3a7a-fb2e-4d44-962b-6d59bc861de7
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	partition 'Customers-9a820bbe-ff6a-4b87-a992-bbb4fb6166a7' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\\Customers.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
				,
				    SelectedColumns = Table.SelectColumns(PromotedHeaders, {"CustomerID", "CustomerName", "Country", "City", "Region"})
				,
				    #"Changed Type" = Table.TransformColumnTypes(SelectedColumns, {{"CustomerID", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

