table Customers
	lineageTag: a57f5099-12e1-47a9-ba29-2402bee8da94

	column CustomerID
		dataType: int64
		lineageTag: 0c831e7f-2589-4b0d-8640-0e01914e93a6
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column CustomerName
		dataType: string
		lineageTag: eb8f0d27-672b-43b5-aa37-bce28f4ec3f9
		summarizeBy: none
		sourceColumn: CustomerName

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 84a8e74d-3dd6-44e0-bb8a-766fc78caa0c
		summarizeBy: none
		sourceColumn: Country
		dataCategory: Country

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: f7934978-151f-4a0f-90ed-d03df1f13c6b
		summarizeBy: none
		sourceColumn: City
		dataCategory: City

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 7272f3ec-81c3-485d-9b32-2b097d15dd1e
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	partition 'Customers-212d2550-bf8c-497f-8501-f36216f560d5' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\\Customers.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
				,
				    SelectedColumns = Table.SelectColumns(PromotedHeaders, {"CustomerID", "CustomerName", "Country", "City", "Region"})
				,
				    #"Changed Type" = Table.TransformColumnTypes(SelectedColumns, {{"CustomerID", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

