table Products
	lineageTag: 47a2037b-d46f-41d4-8d0b-39dec4d2c372

	column ProductID
		dataType: int64
		lineageTag: cce58e7e-f9c2-4c4b-a435-316f300cc649
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: 927e126c-363d-4f53-9db5-fc6c099d6514
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column CategoryID
		dataType: int64
		lineageTag: dcfff6d4-2891-46aa-bace-7272503ccf76
		summarizeBy: none
		sourceColumn: CategoryID

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: double
		lineageTag: 6b2de643-cc82-48c2-b22b-c4309580746a
		summarizeBy: none
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

	partition 'Products-2534a465-c41a-4c18-9df5-9a48dcb0c05a' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\\Products.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
				,
				    SelectedColumns = Table.SelectColumns(PromotedHeaders, {"ProductID", "ProductName", "CategoryID", "UnitPrice"})
				,
				    #"Changed Type" = Table.TransformColumnTypes(SelectedColumns, {{"ProductID", Int64.Type}, {"CategoryID", Int64.Type}, {"UnitPrice", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

