table Products
	lineageTag: c776fdb1-7d8e-4eb7-ae69-7e6735723068

	column ProductID
		dataType: int64
		lineageTag: f24fd58c-accd-48ec-9d5b-4706aba16352
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: f99d4cd7-ced3-4750-a19d-022b33c95265
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column CategoryID
		dataType: int64
		lineageTag: 9df22956-1d74-4caf-83a5-77820f0f589a
		summarizeBy: none
		sourceColumn: CategoryID

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: double
		lineageTag: 10900217-f6f8-4b6b-92bb-6311f1c2979e
		summarizeBy: none
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

	partition 'Products-4b269ca0-511e-4f3d-a3ca-8c5094228c59' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\\Products.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
				,
				    SelectedColumns = Table.SelectColumns(PromotedHeaders, {"ProductID", "ProductName", "CategoryID", "UnitPrice"})
				,
				    #"Changed Type" = Table.TransformColumnTypes(SelectedColumns, {{"ProductID", Int64.Type}, {"CategoryID", Int64.Type}, {"UnitPrice", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

