table Sales
	lineageTag: 7a699818-2b1f-431f-b99b-a6e16ec4d49f

	measure 'CA Total' = SUM('Sales'[Amount])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 44cfccf6-58eb-4c2e-9e92-190e66e315c1

	measure 'Qté Totale' = SUM('Sales'[Quantity])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 674c7544-744d-46bd-8ac5-c5d09cdc094d

	measure 'Année en cours' = "Year(Today())"
		lineageTag: 06c2d7da-75a7-44e5-97ef-21bccd3500d7

	column SaleID
		dataType: int64
		lineageTag: 22990535-1916-478d-8ffd-f0eb361d5ab1
		summarizeBy: none
		sourceColumn: SaleID

		annotation SummarizationSetBy = Automatic

	column CustomerID
		dataType: int64
		lineageTag: 3a00c2b0-2c54-48ad-9adc-b8281326033e
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column ProductID
		dataType: int64
		lineageTag: 7ea3b46d-d896-4c93-be28-3d029c940351
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: dateTime
		lineageTag: e32db441-68cb-43a2-a191-48986020a9db
		summarizeBy: none
		sourceColumn: OrderDate

		annotation SummarizationSetBy = Automatic

	column Amount
		dataType: double
		lineageTag: 4fc3febb-76ae-4836-aad2-5087d2bd6d01
		summarizeBy: none
		sourceColumn: Amount

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		lineageTag: 908961c9-89ee-4264-9af9-3ea120c54113
		summarizeBy: none
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	partition 'Sales-bdb8c5a8-cf25-43bf-ae2d-c3016b0a1888' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\\Sales.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
				,
				    SelectedColumns = Table.SelectColumns(PromotedHeaders, {"SaleID", "CustomerID", "ProductID", "OrderDate", "Amount", "Quantity"})
				,
				    #"Changed Type" = Table.TransformColumnTypes(SelectedColumns, {{"SaleID", Int64.Type}, {"CustomerID", Int64.Type}, {"ProductID", Int64.Type}, {"OrderDate", type datetime}, {"Amount", type number}, {"Quantity", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

