table Sales
	lineageTag: 52f49e2e-e9bc-4606-937c-d94d2ca81092

	measure 'CA Total' = SUM('Sales'[Amount])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: e36053bb-e444-4314-a599-acdd551c9c89

	measure 'Qté Totale' = SUM('Sales'[Quantity])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 8f5a4056-a71e-476c-845e-bac73ac69940

	measure 'Année en cours' = "Year(Today())"
		lineageTag: 843db65f-0f65-4a93-960b-bd109f4c22a9

	column SaleID
		dataType: int64
		lineageTag: 063fcbd2-4e07-4a28-b001-12b72aadfa8b
		summarizeBy: none
		sourceColumn: SaleID

		annotation SummarizationSetBy = Automatic

	column CustomerID
		dataType: int64
		lineageTag: 878f9c8c-e344-4d2d-8a69-856cd33ae5bd
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column ProductID
		dataType: int64
		lineageTag: cd959656-3c01-4dea-9c97-83e6d91fb57e
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: dateTime
		lineageTag: 1105607e-6f38-47cb-bc6e-050160cee118
		summarizeBy: none
		sourceColumn: OrderDate

		annotation SummarizationSetBy = Automatic

	column Amount
		dataType: double
		lineageTag: 1dff9313-af84-42a6-8b66-bd06996183e9
		summarizeBy: none
		sourceColumn: Amount

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		lineageTag: 73abc494-179b-434d-ae03-bba3c456f772
		summarizeBy: none
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	partition 'Sales-441ce27d-40ea-4efc-969a-4f04d800a668' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\\Sales.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
				,
				    SelectedColumns = Table.SelectColumns(PromotedHeaders, {"SaleID", "CustomerID", "ProductID", "OrderDate", "Amount", "Quantity"})
				,
				    #"Changed Type" = Table.TransformColumnTypes(SelectedColumns, {{"SaleID", Int64.Type}, {"CustomerID", Int64.Type}, {"ProductID", Int64.Type}, {"OrderDate", type datetime}, {"Amount", type number}, {"Quantity", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

