// Power Query M expression for table: Customers
// Auto-generated by Qlik-to-Power BI migration

let
    Source = Sql.Database("localhost", "master"),
    Table = Source{[Schema="dbo",Item="Customers"]}[Data],
    #"Changed Type" = Table.TransformColumnTypes(Table, {{"CustomerID", Int64.Type}})
in
    #"Changed Type"
