// Power Query M expression for table: SalesReps
// Auto-generated by Qlik-to-Power BI migration

let
    Source = Sql.Database("localhost", "master"),
    Table = Source{[Schema="dbo",Item="SalesReps"]}[Data],
    #"Changed Type" = Table.TransformColumnTypes(Table, {{"SalesRepID", Int64.Type}})
in
    #"Changed Type"
