// Power Query M expression for table: Categories
// Auto-generated by Qlik-to-Power BI migration

let
    // TODO: Configure data source for table "Categories"
    Source = #table({"CategoryID", "CategoryName", "Description"}, {}),
    #"Changed Type" = Table.TransformColumnTypes(Source, {{"CategoryID", Int64.Type}})
in
    #"Changed Type"
