// Power Query M expression for table: Customers
// Auto-generated by Qlik-to-Power BI migration

let
    Source = Excel.Workbook(File.Contents(DataFolder & "\\Customers.xlsx"), null, true),
    Sheet1 = Source{{[Item="Sheet1",Kind="Sheet"]}}[Data],
    PromotedHeaders = Table.PromoteHeaders(Sheet1, [PromoteAllScalars=true])
,
    SelectedColumns = Table.SelectColumns(PromotedHeaders, {"CustomerID", "CustomerName", "Country", "City", "Region"})
,
    #"Changed Type" = Table.TransformColumnTypes(SelectedColumns, {{"CustomerID", Int64.Type}})
in
    #"Changed Type"
