table Products
	lineageTag: 8bc525d9-a62e-4fd6-a105-192178d63733

	column ProductID
		dataType: int64
		lineageTag: ab50f798-2e4a-41dd-88e0-46a7eb930841
		summarizeBy: sum
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: d455a6e4-091b-42a1-ab92-a2fdd0ff828b
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 90a27e1d-9913-420d-8c4c-9e9d5146be22
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column SubCategory
		dataType: string
		lineageTag: 9c5e9f78-904b-4b30-91b1-dcb0c6f34bb7
		summarizeBy: none
		sourceColumn: SubCategory

		annotation SummarizationSetBy = Automatic

	column Brand
		dataType: string
		lineageTag: 084dcaf1-6c45-4e56-8335-d5930d2a80a6
		summarizeBy: none
		sourceColumn: Brand

		annotation SummarizationSetBy = Automatic

	column UnitCost
		dataType: decimal
		lineageTag: 60a02c39-62e4-49b9-84f8-827f42dec8cb
		summarizeBy: none
		sourceColumn: UnitCost

		annotation SummarizationSetBy = Automatic

	column ListPrice
		dataType: decimal
		lineageTag: a297a945-1571-4086-94b6-a925732b7209
		summarizeBy: none
		sourceColumn: ListPrice

		annotation SummarizationSetBy = Automatic

	partition 'Products-749000dc-0c0e-4181-9b3f-01591939e760' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("data/Sales.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {{"ProductID", type text}, {"ProductName", type text}, {"Category", type text}, {"SubCategory", type text}, {"Brand", type text}, {"UnitCost", type text}, {"ListPrice", type text}})
				in
				    ChangedTypes

	annotation PBI_ResultType = Table

