table Returns
	lineageTag: e2c46d38-582c-463a-bd09-a872e24dfdf8

	column ReturnID
		dataType: int64
		lineageTag: ac0d42bf-ec11-4b69-93cf-de151e94e22e
		summarizeBy: sum
		sourceColumn: ReturnID

		annotation SummarizationSetBy = Automatic

	column OrderID
		dataType: int64
		lineageTag: 30bf3fd2-61f2-4f8d-99db-072fac24a036
		summarizeBy: sum
		sourceColumn: OrderID

		annotation SummarizationSetBy = Automatic

	column ReturnDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 83870264-ef38-427c-8d5e-192f61c67501
		summarizeBy: none
		sourceColumn: ReturnDate
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column ReturnReason
		dataType: string
		lineageTag: c9a84b03-3c4d-420e-b628-d52fffded9a2
		summarizeBy: none
		sourceColumn: ReturnReason

		annotation SummarizationSetBy = Automatic

	column RefundAmount
		dataType: decimal
		lineageTag: 55e133ac-8d03-4461-b76a-0c2e3c2bed77
		summarizeBy: none
		sourceColumn: RefundAmount

		annotation SummarizationSetBy = Automatic

	partition 'Returns-59bd5494-059a-487f-9a4e-7f2862e0f3bd' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("data/Sales.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {{"ReturnID", type text}, {"OrderID", type text}, {"ReturnDate", type text}, {"ReturnReason", type text}, {"RefundAmount", type text}})
				in
				    ChangedTypes

	annotation PBI_ResultType = Table

