table Calendar
	lineageTag: 5603ffdf-61a3-45e0-99a7-c33ba538e8ca

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: fa922995-56e3-4842-af63-011e7f6c1838
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 5a70e80d-fb9b-42a4-8ae9-21158a1c9995
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: ac9ed015-acb8-40ba-a81e-658dcb3c9857
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: f5927def-0894-45f5-b5df-2a2b411215ec
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: f9406dbd-75f6-45b3-9329-06ea3202fab7
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 77c89c2b-c06f-484b-abf6-aa85e3b1e3c1
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: ca203c7f-e220-4919-979a-6847715332ec
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 07f35708-deb7-476a-b493-c012cb7df5e7
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 65662210-ae3f-47a3-9bcb-81af633f624c

		level Year
			ordinal: 0
			column: Year
			lineageTag: c7929fa5-038e-4ec7-8223-266571957d56

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 19316d84-ef9e-47ff-bbaa-47fb007dee2d

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 071845ad-dfbd-4013-9ff9-0a4d21662aee

		level Day
			ordinal: 3
			column: Day
			lineageTag: fd206140-14a6-4a78-a173-750ab380b2ab


	partition 'Calendar-12973462-87bc-41d2-85f9-f854389bca1d' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

