// Power Query M expression for table: Products
// Auto-generated by Qlik-to-Power BI migration

let
    Source = Qvd.Document(File.Contents(DataFolder & "\\Products.qvd"))
,
    SelectedColumns = Table.SelectColumns(Source, {"ProductID", "ProductName", "CategoryID", "UnitPrice"})
,
    #"Changed Type" = Table.TransformColumnTypes(SelectedColumns, {{"ProductID", Int64.Type}, {"CategoryID", Int64.Type}, {"UnitPrice", type number}})
in
    #"Changed Type"
