table Calendar
	lineageTag: 9d122c0e-95df-4a69-88e5-7146077139df

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: ab584299-9892-40c9-b199-4bbe9b433cae
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 9775bbe1-ee8d-46ff-a285-5d2b6e8f3050
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 6c402159-dcd9-4d06-b142-8890dd7b11ba
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: c04c0a66-595e-44a4-beeb-5260763c4495
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 910af818-8a95-447a-bc0d-ade72c51c548
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: d037d9d5-48f7-46b4-9ace-3a173bd9a6e8
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 642be657-c69f-42f0-b514-a7abbe0a6101
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: a3e6d926-a44b-4d32-9a20-1d6994fcae4b
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: c43b5307-8999-473c-a8b6-04e117c3258a

		level Year
			ordinal: 0
			column: Year
			lineageTag: a87da058-8afc-4ea1-a571-d97de81dc051

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 43e95b67-031a-4345-8adb-3369a29de74f

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: e071b8c5-42ed-4363-a73c-64702e2286bf

		level Day
			ordinal: 3
			column: Day
			lineageTag: df946a1d-6602-4935-af59-2261222d17a6


	partition 'Calendar-8c170916-45ab-47f9-a960-4c824625a3ea' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

