table Products
	lineageTag: a6129669-52e5-4eaa-ade8-3ddc780afc0b

	column ProductID
		dataType: int64
		lineageTag: 9adabfca-cfd1-45cb-b6bd-b1f6b2fd2ff2
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: 6b45b417-3f19-4b93-aa57-8d5fc9a2d936
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 8cbcc18b-75aa-46ee-9af2-2ad7d3aaf58f
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column SubCategory
		dataType: string
		lineageTag: 9bdd7e3e-3938-441f-83fe-f5d208f09c5f
		summarizeBy: none
		sourceColumn: SubCategory

		annotation SummarizationSetBy = Automatic

	column UnitCost
		dataType: double
		lineageTag: 814c29fe-666b-4906-80a8-39c406a17d40
		summarizeBy: none
		sourceColumn: UnitCost

		annotation SummarizationSetBy = Automatic

	partition 'Products-5f02469e-9971-44c1-a882-6299de3bc446' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\\Products.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
				,
				    SelectedColumns = Table.SelectColumns(PromotedHeaders, {"ProductID", "ProductName", "Category", "SubCategory", "UnitCost"})
				,
				    #"Changed Type" = Table.TransformColumnTypes(SelectedColumns, {{"ProductID", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

